# Generated by Django 4.1.3 on 2022-11-06 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CopyWrite',
            new_name='CopyRight',
        ),
        migrations.AlterModelOptions(
            name='copyright',
            options={'verbose_name_plural': 'CopyRight'},
        ),
    ]
