# Generated by Django 4.1.3 on 2022-11-06 19:04

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_contactinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinformation',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='BD'),
        ),
    ]
