# Generated by Django 4.1.3 on 2022-11-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_bannerportion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerportion',
            name='banner_img',
            field=models.ImageField(blank=True, null=True, upload_to='banner'),
        ),
    ]
